/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/book.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Book Json
         * @description 옛 스냅샷 그대로. 화면이 /api/view 로 옮겨 갈 때까지 남긴다.
         */
        get: operations["book_json_book_json_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feed.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Feed Json */
        get: operations["feed_json_feed_json_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/view": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api View
         * @description ★화면이 그릴 값. 활성 필터·무크로스·최우선·중앙값·히트맵을 여기서 계산한다.
         *
         *     lane: ktb | msb | nhb | cr · ttl: def | half | inf
         *     cls·rt: 크레딧에서 고른 종별·등급(등급 커브 선택에 쓴다)
         */
        get: operations["api_view_api_view_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Events
         * @description SSE. 책이 바뀔 때만 민다. 15초 조용하면 하트비트(끊김 오인 방지).
         */
        get: operations["events_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Index
         * @description 화면은 문턱 밖이다 — 비밀은 데이터이지 화면이 아니다.
         */
        get: operations["index__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BondRow
         * @description 종목 한 줄 — 서버가 활성 필터·무크로스·최우선·mid 를 계산해 준 것.
         */
        BondRow: {
            /** C */
            c: string;
            /** Nm */
            nm?: string | null;
            /** Full */
            full?: string | null;
            /** Alias */
            alias?: string | null;
            /** Ten */
            ten?: string | null;
            /** Mat */
            mat?: string | null;
            /** Mp */
            mp?: number | null;
            /** Mpd */
            mpd?: string | null;
            /** @description 최우선 오퍼 */
            fa?: components["schemas"]["Quote"] | null;
            /** @description 최우선 비드 */
            fb?: components["schemas"]["Quote"] | null;
            /** Mid */
            mid?: number | null;
            /**
             * Fill
             * @description 당일 마지막 체결 {t, y}
             */
            fill?: {
                [key: string]: unknown;
            } | null;
            /**
             * Bench
             * @default false
             */
            bench: boolean;
            /**
             * Next
             * @default false
             */
            next: boolean;
            /**
             * Today
             * @default false
             */
            today: boolean;
            /**
             * N
             * @default 0
             */
            n: number;
            /**
             * Nq
             * @default 0
             */
            nq: number;
            /**
             * Npx
             * @default 0
             */
            npx: number;
            /**
             * Hn
             * @default 0
             */
            hn: number;
            /**
             * Pv
             * @description 어제 책의 그 종목
             */
            pv?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * CreditBucket
         * @description 종별×등급 버킷. 값은 중앙값이다.
         */
        CreditBucket: {
            /** K */
            k: string;
            /** Cls */
            cls: string;
            /** Rt */
            rt: string;
            /**
             * Est
             * @description 등급이 문면이 아니라 집계에서 온 것
             * @default false
             */
            est: boolean;
            /** N */
            n: number;
            /**
             * Mb
             * @default 0
             */
            mb: number;
            /** Bp Med */
            bp_med?: number | null;
            /** Ytm Med */
            ytm_med?: number | null;
            /** Ttm Lo */
            ttm_lo?: number | null;
            /** Ttm Hi */
            ttm_hi?: number | null;
        };
        /** Curve */
        Curve: {
            /** Offers */
            offers: components["schemas"]["CurveOffer"][];
            /**
             * Mp Line
             * @description [[잔존, 민평 중앙값, 표본수], …]
             */
            mp_line: unknown[][];
            /**
             * Mp N
             * @default 0
             */
            mp_n: number;
        };
        /** CurveOffer */
        CurveOffer: {
            /** N */
            n?: string | null;
            /** Ttm */
            ttm?: number | null;
            /** Ytm */
            ytm?: number | null;
            /** Bpe */
            bpe?: number | null;
            /** A */
            a?: number | null;
            /**
             * Mb
             * @default 0
             */
            mb: number;
            /** Lvl */
            lvl?: ("quoted" | "conv" | "est") | null;
        };
        /** FeedPage */
        FeedPage: {
            /** Feed */
            feed: components["schemas"]["FeedRow"][];
            /** N Seq */
            n_seq: number;
        };
        /**
         * FeedRow
         * @description 메시지 한 줄. 파싱 결과를 원문과 나란히 흘린다.
         */
        FeedRow: {
            /**
             * I
             * @description 적재 일련번호. 화면이 이걸로 이어 붙인다
             */
            i: number;
            /** T */
            t: number;
            /**
             * R
             * @description 방
             */
            r?: string | null;
            /**
             * K
             * @description 종류 QUOTE·AXE·CONFIRM·INQUIRY·THANKS·OTHER
             */
            k?: string | null;
            /** Sec */
            sec?: string | null;
            /** N */
            n?: string | null;
            /** Code */
            code?: string | null;
            /** S */
            s?: ("S" | "B") | null;
            /** Y */
            y?: number | null;
            /** Bp */
            bp?: number | null;
            /** A */
            a?: number | null;
            /** Asrc */
            asrc?: ("stated" | "implied" | "bare" | "default" | "oddlot" | "inherit") | null;
            /** Atmp */
            atmp?: boolean | null;
            /** Csrc */
            csrc?: ("stated" | "level" | "prev") | null;
            /** Lvl */
            lvl?: ("quoted" | "conv" | "est") | null;
            /** D */
            d?: string | null;
            /**
             * Bk
             * @description 딜러 키(가림 뒤 라벨)
             */
            bk?: string | null;
            /**
             * H
             * @description 하우스(가림 뒤 라벨)
             */
            h?: string | null;
            /** Raw */
            raw?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Heat */
        Heat: {
            /** Cells */
            cells: {
                [key: string]: components["schemas"]["HeatCell"];
            };
            /**
             * Stale
             * @description 통안 민평이 그날 것이 아니다
             * @default false
             */
            stale: boolean;
            /** Rows */
            rows: unknown[][];
            /** Buckets */
            buckets: string[];
        };
        /** HeatCell */
        HeatCell: {
            /** Med */
            med?: number | null;
            /**
             * N
             * @default 0
             */
            n: number;
            /** Lo */
            lo?: number | null;
            /** Hi */
            hi?: number | null;
            /**
             * Est
             * @description 그 칸에 든 «추정»(끝전 0.5 가정) 건수
             * @default 0
             */
            est: number;
        };
        /**
         * Quote
         * @description 국고·통안·국민주택의 한 호가. (딜러, 방향, 종목) 하나에 하나뿐이다 — 절대값 교체.
         */
        Quote: {
            /**
             * T
             * @description 장중 초(00:00:00 부터)
             */
            t: number;
            /**
             * S
             * @description S=매도(오퍼) · B=매수(비드)
             */
            s?: ("S" | "B") | null;
            /**
             * Y
             * @description 수익률(%). 없으면 레벨 미상이다
             */
            y?: number | null;
            /**
             * Code
             * @description 국고 '25-10' · 통안 만기일 · 국주 사다리 칸
             */
            code?: string | null;
            /**
             * A
             * @description 수량(억). 표기가 없으면 기본단위 100
             */
            a?: number | null;
            /** Asrc */
            asrc?: ("stated" | "implied" | "bare" | "default" | "oddlot" | "inherit") | null;
            /**
             * D
             * @description 딜러 표시명. 가림이 켜져 있으면 'H01-2'
             */
            d?: string | null;
            /**
             * K
             * @description 딜러 키. 가림이 켜져 있으면 'K001'
             */
            k?: string | null;
            /**
             * Atmp
             * @description 레벨 없이 «민평에» 한다는 뜻의 호가
             */
            atmp?: boolean | null;
            /**
             * Mp
             * @description 그 종목의 전일 민평(통안·국주만 싣는다)
             */
            mp?: number | null;
            /**
             * Mpd
             * @description 그 민평의 일자. 오늘이 아니면 «전일 대비»가 아니다
             */
            mpd?: string | null;
            /**
             * Qr
             * @description 축약호가 원문(국주)
             */
            qr?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * View
         * @description `/api/view` 의 응답. 화면은 이걸 그대로 그린다.
         */
        View: {
            /** Now */
            now?: string | null;
            /** T */
            T: number;
            /**
             * Ttl Mode
             * @default def
             * @enum {string}
             */
            ttl_mode: "def" | "half" | "inf";
            /** Ver */
            ver?: number | null;
            /** Counts */
            counts: {
                [key: string]: number;
            };
            heat: components["schemas"]["Heat"];
            /**
             * Rows
             * @description lane 이 ktb·msb·nhb 일 때
             */
            rows?: components["schemas"]["BondRow"][] | null;
            /**
             * Buckets
             * @description lane 이 cr 일 때
             */
            buckets?: components["schemas"]["CreditBucket"][] | null;
            curve?: components["schemas"]["Curve"] | null;
            /**
             * Mtx Group
             * @description credit_matrix 의 bond_type(등급 커브)
             */
            mtx_group?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: {
                t?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    book_json_book_json_get: {
        parameters: {
            query?: {
                t?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    feed_json_feed_json_get: {
        parameters: {
            query?: {
                t?: string | null;
                since?: number;
                limit?: number;
                h?: string | null;
                d?: string | null;
                k?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_view_api_view_get: {
        parameters: {
            query?: {
                t?: string | null;
                lane?: string;
                ttl?: string;
                cls?: string | null;
                rt?: string | null;
                T?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["View"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_events_get: {
        parameters: {
            query?: {
                t?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    index__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
}
