/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/book.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Book Json
         * @description 옛 스냅샷 그대로. 화면이 /api/view 로 옮겨 갈 때까지 남긴다.
         */
        get: operations["book_json_book_json_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feed.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Feed Json */
        get: operations["feed_json_feed_json_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/view": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api View
         * @description ★화면이 그릴 값. 활성 필터·무크로스·최우선·중앙값·히트맵을 여기서 계산한다.
         *
         *     lane: ktb | msb | nhb | cr · ttl: def | half | inf
         *     cls·rt: 크레딧에서 고른 종별·등급(등급 커브 선택에 쓴다)
         */
        get: operations["api_view_api_view_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alarms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Alarms
         * @description 「방금 온 싼 오퍼」만. **1KB 아래**라 화면이 어느 탭에 있어도 계속 들을 수 있다.
         *
         *     왜 `/api/view` 로 안 하는가 — `lane=cr` 응답은 오퍼 825개를 실어 **455KB** 다(실측
         *     2026-10-01). 알람 하나 보려고 그걸 5초마다 받으면 [OWNER 2026-09-23 「렉이 미친듯이
         *     걸림」] 을 다시 만든다. 그 교훈이 SSE 의 `lite=1` 을 만든 것과 같은 자리다.
         *
         *     ★수는 `kbond_view.alarm_view` **한 곳**이 낸다 — `/api/view` 의 `alarms` 와 같은
         *       함수다. 두 곳이 각자 유도하면 한쪽만 고치게 된다(`verify_v4` [M2] 가 대조한다).
         *     ⚠빈 목록은 「없다」가 아니라 「창 안에 안 왔다」다 — 60초 창이면 대부분의 순간에 0건이다.
         *       화면은 **쌓아야** 하고, 이 응답이 비었다고 쌓인 것을 지우면 안 된다.
         */
        get: operations["api_alarms_api_alarms_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/px_hist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Px Hist
         * @description 한 종목의 «어제까지» 시세 테이프 — 분 단위 매도·매수와 그날의 전일 민평.
         *
         *     [OWNER 2026-10-01] 「어제자랑 연결해서 최대 1년까지」. 오늘은 `/api/view` 의 `px` 가
         *     내고 화면이 둘을 잇는다. 책(스냅샷)을 안 읽는다 — 아침에 구운 파케이만 읽으므로
         *     장중엔 값이 안 바뀐다. 그래서 캐시를 허락한다(`/api/view` 는 no-store).
         *
         *     days: 마지막 n 영업일(0 = 전부) · before: 이 날(exclusive) 앞까지 — 화면이 «오늘» 을 넘긴다.
         */
        get: operations["api_px_hist_api_px_hist_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Events
         * @description SSE. 책이 바뀔 때만 민다. 15초 조용하면 하트비트(끊김 오인 방지).
         *
         *     ★`lite=1` 이면 «화면이 실제로 읽는 것» 만 민다 — now·n_msg·n_seq·feed.
         *       [OWNER 2026-09-23 「렉이 미친듯이 걸림」] 책이 1.2MB 인데 매초 통째로
         *       밀고 있었고, 새 화면이 그 프레임에서 쓰는 건 feed 와 n_msg 둘뿐이었다.
         *       나머지를 매초 JSON.parse 하고 버리던 것이 렉이었다.
         *       ⚠기본(lite=0)은 그대로 둔다 — 옛 화면(/)은 프레임 전체를 읽는다.
         */
        get: operations["events_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Index
         * @description 화면은 문턱 밖이다 — 비밀은 데이터이지 화면이 아니다.
         */
        get: operations["index__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActBin */
        ActBin: {
            /** T */
            t: number;
            /**
             * N
             * @description 막대 높이 — 화면과 같게 앞 둘의 합
             * @default 0
             */
            n: number;
            /**
             * Tot
             * @description 척도용 합계
             * @default 0
             */
            tot: number;
        };
        /**
         * AlarmHit
         * @description 「방금 온 싼 오퍼」 한 건. `kbond_view.alarm_hits` 가 낸다.
         *
         *     ★**모집단은 «거르기 전 크레딧 책»** 이다 — 화면이 어떤 pill·등급을 보고 있어도 같은
         *       답이 온다. 필터에 따라 울리거나 안 울리면 그건 알람이 아니다.
         *     ★**상태가 없다** — 호가의 도착 시각으로 나이를 재서 판정하므로 같은 입력에 같은 답이다.
         *       그래서 **같은 도착이 창(60초) 동안 여러 번 실려 온다**(5초 폴이면 최대 12번).
         *       소비자가 `key` 로 접는다.
         */
        AlarmHit: {
            /**
             * Key
             * @description 한 도착을 가리키는 열쇠 «딜러|종목|도착초». 이것으로 접는다
             */
            key: string;
            /**
             * N
             * @description 종목/발행체 표시명
             */
            n?: string | null;
            /**
             * D
             * @description 딜러 표시명
             */
            d?: string | null;
            /**
             * Cls
             * @description 종별 — 위험순
             */
            cls?: string | null;
            /**
             * Rt
             * @description 신용등급
             */
            rt?: string | null;
            /**
             * Ttm
             * @description 잔존(년)
             */
            ttm?: number | null;
            /**
             * A
             * @description 수량(억)
             */
            a?: number | null;
            /**
             * Age
             * @description 나이(초) = 책의 T − 호가 도착 시각. 창은 60초(1분 벼랑)
             */
            age?: number | null;
            /**
             * Val
             * @description 이 오퍼의 값 — 무리가 커브반영을 가졌으면 bpc, 아니면 bpe
             */
            val?: number | null;
            /**
             * Med
             * @description 그 무리의 중앙값(같은 자로 잰 것)
             */
            med?: number | null;
            /**
             * Dev
             * @description 무리 중앙 대비 편차(bp). 싸다 = 양수. 이것이 문턱을 넘었다
             */
            dev?: number | null;
            /**
             * Won
             * @description 그 편차가 **단가 몇 원인가**(액면 1만원). 100억 기준은 ×1e6. ★bp 는 짧은 잔존에서 돈이 아니다 — 잔존 0.01년의 3bp 는 100억에 3만원이고 1년이면 289만원이다(1,000배). 환산표는 끝전 환산이 쓰는 그 한 벌(`enrich_kbond_quotes.won_to_bp`)이고, 못 꽂혔으면 `None` 이다 (0 이 아니다 — 「못 쟀다」와 「0원」은 다른 말이다)
             */
            won?: number | null;
            /**
             * Adj
             * @description 커브 반영값으로 쟀나(아니면 민평대비). 무리 안에서 자는 하나다
             */
            adj?: boolean | null;
            /**
             * Pk
             * @description 무리 이름
             */
            pk?: string | null;
            /**
             * Pr
             * @description 그 무리 안 순위
             */
            pr?: number | null;
            /**
             * Pn
             * @description 그 무리에서 값을 부른 오퍼 수
             */
            pn?: number | null;
            /**
             * Est
             * @description 무리의 등급이 문면이 아니라 집계에서 온 것 — 화면이 그 사실을 적는다
             */
            est?: boolean | null;
        };
        /**
         * Alarms
         * @description `/api/alarms` 의 응답 — 알람만 내는 가벼운 자리.
         *
         *     왜 따로 있는가: `/api/view?lane=cr` 은 오퍼 825개를 실어 **455KB** 다(실측). 알람만
         *     보려고 그걸 5초마다 받으면 2026-09-23 의 「렉이 미친듯이 걸림」을 다시 만든다.
         *     이 응답은 **1KB 아래**라 화면이 어느 탭에 있어도 계속 들을 수 있다.
         *     ★`/api/view` 의 `alarms` 와 **같은 함수**(`kbond_view.alarm_view`)가 낸다 —
         *       두 곳이 각자 유도하면 한쪽만 고치게 된다. `verify_v4` [M2] 가 둘을 대조한다.
         */
        Alarms: {
            /** Now */
            now?: string | null;
            /** T */
            T: number;
            /** Ver */
            ver?: number | null;
            /**
             * Alarms
             * @description 창 안에 온 것. **대부분의 순간에 비어 있다**(실측)
             * @default []
             */
            alarms: components["schemas"]["AlarmHit"][];
            /**
             * Alarm N Bp
             * @description 지금 걸린 문턱(bp) — 무리 중앙 대비. 화면이 이 값을 적고 스스로 정하지 않는다
             */
            alarm_n_bp: number;
        };
        /**
         * Axis
         * @description 레벨 없는 «관심». 종목·방향은 정해졌는데 값이 없는 호가 [OWNER 2026-09-07].
         *
         *     09-01 판정으로 «호가» 라 부르지 않으므로 책에는 안 들어간다 — 이 목록에만 있다.
         */
        Axis: {
            /** T */
            t: number;
            /** Lane */
            lane?: ("ktb" | "msb" | "nhb" | "cr" | "muni") | null;
            /** Code */
            code?: string | null;
            /** N */
            n?: string | null;
            /** S */
            s?: ("S" | "B") | null;
            /** A */
            a?: number | null;
            /** Asrc */
            asrc?: ("stated" | "implied" | "bare" | "default" | "oddlot" | "inherit") | null;
            /** D */
            d?: string | null;
            /** K */
            k?: string | null;
        };
        /**
         * Basket
         * @description 범주 콜 = 크레딧의 «매수면». 종목을 안 찍고 (잔존, 섹터, 등급)으로 온다.
         */
        Basket: {
            /** T */
            t: number;
            /** Lo */
            lo?: number | null;
            /** Hi */
            hi?: number | null;
            /** Sec */
            sec?: string | null;
            /** Rt */
            rt?: string | null;
            /** A */
            a?: number | null;
            /** Asrc */
            asrc?: ("stated" | "implied" | "bare" | "default" | "oddlot" | "inherit") | null;
            /** D */
            d?: string | null;
            /**
             * Ms
             * @description 이 니즈에 맞는 오퍼 수
             */
            ms?: number | null;
            /**
             * Bo
             * @description 그중 가장 싼 것
             */
            bo?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * BondRow
         * @description 종목 한 줄 — 서버가 활성 필터·무크로스·최우선·mid 를 계산해 준 것.
         */
        BondRow: {
            /** C */
            c: string;
            /** Nm */
            nm?: string | null;
            /** Full */
            full?: string | null;
            /** Alias */
            alias?: string | null;
            /** Ten */
            ten?: string | null;
            /** Mat */
            mat?: string | null;
            /** Mp */
            mp?: number | null;
            /** Mpd */
            mpd?: string | null;
            /** @description 최우선 오퍼 */
            fa?: components["schemas"]["Quote"] | null;
            /** @description 최우선 비드 */
            fb?: components["schemas"]["Quote"] | null;
            /** Mid */
            mid?: number | null;
            /**
             * Fill
             * @description 당일 마지막 체결 {t, y}
             */
            fill?: {
                [key: string]: unknown;
            } | null;
            /**
             * Bench
             * @default false
             */
            bench: boolean;
            /**
             * Next
             * @default false
             */
            next: boolean;
            /**
             * Today
             * @default false
             */
            today: boolean;
            /**
             * N
             * @default 0
             */
            n: number;
            /**
             * Nq
             * @default 0
             */
            nq: number;
            /**
             * Npx
             * @default 0
             */
            npx: number;
            /**
             * Hn
             * @default 0
             */
            hn: number;
            /**
             * Pv
             * @description 어제 책의 그 종목
             */
            pv?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * BookInfo
         * @description 책이 말하는 것 — 오늘 귀속 체결에서 잰 셋(국고·통안). 값은 엔진이 체결 순간에 재 둔 것.
         *     국고 전 이력 실측은 RESULT_book_dynamics_2026-09-15.md.
         */
        BookInfo: {
            /**
             * N
             * @description 귀속된 체결 수
             * @default 0
             */
            n: number;
            /**
             * N Eff
             * @default 0
             */
            n_eff: number;
            /**
             * Eff Med
             * @description 유효 반스프레드 중앙 bp
             */
            eff_med?: number | null;
            /**
             * N Qs
             * @default 0
             */
            n_qs: number;
            /**
             * Qs Half Med
             * @description 체결 시점 호가 반스프레드 중앙 bp
             */
            qs_half_med?: number | null;
            /**
             * N Ab
             * @default 0
             */
            n_ab: number;
            /**
             * At Best Pct
             * @description 최우선 레벨에서 난 비율 %
             */
            at_best_pct?: number | null;
            /**
             * N Imb
             * @description 불균형을 잰 체결 — 문면에 종목이 있는 것(csrc=stated)만
             * @default 0
             */
            n_imb: number;
            /**
             * N Imb Prev
             * @description 불균형은 있으나 맨 ㅎㅈ 를 직전 호가에 붙인 것(csrc=prev) — 연구가 못 잰 모집단이라 뺀 수
             * @default 0
             */
            n_imb_prev: number;
            /**
             * P B By Imb
             * @description 직전 불균형 구간(오퍼 우세·균형·비드 우세)별 사 감 비율
             * @default {}
             */
            p_b_by_imb: {
                [key: string]: components["schemas"]["ImbCell"];
            };
        };
        /**
         * ClsPill
         * @description 분류 줄의 한 칸. 순서가 곧 «구성» 이다 — 국고·통안 다음 위험순 계열 여덟.
         *     [OWNER 2026-09-11] 히트맵 행과 같은 축으로 세웠다.
         */
        ClsPill: {
            /** Cls */
            cls: string;
            /**
             * N
             * @description 살아 있는 건수(계열) 또는 칸이 서는 종목 수(국고·통안)
             * @default 0
             */
            n: number;
            /**
             * Gov
             * @description 계열이 아니라 레인이다 — 등급 대신 만기 버킷으로 접힌다
             * @default false
             */
            gov: boolean;
        };
        /**
         * CreditBucket
         * @description 종별×등급 버킷. 값은 중앙값이다.
         *     ★국고·통안을 고르면 같은 모양에 «등급» 자리가 만기 버킷(~1년·1~2…)으로 온다.
         */
        CreditBucket: {
            /** K */
            k: string;
            /** Cls */
            cls: string;
            /** Rt */
            rt: string;
            /**
             * Est
             * @description 등급이 문면이 아니라 집계에서 온 것
             * @default false
             */
            est: boolean;
            /**
             * Gov
             * @description 국고·통안 버킷 — n 의 단위가 «건» 이 아니라 «종» 이다
             * @default false
             */
            gov: boolean;
            /**
             * Stale
             * @description 그 칸에 «민평이 그날 것이 아닌» 종목이 있다(통안 최신물)
             * @default false
             */
            stale: boolean;
            /** N */
            n: number;
            /**
             * Nat
             * @description 그중 «민평에» 오퍼 수 — 중앙값에서는 뺀다 [OWNER 2026-09-07]
             * @default 0
             */
            nat: number;
            /**
             * Mb
             * @default 0
             */
            mb: number;
            /** Bp Med */
            bp_med?: number | null;
            /**
             * Bpc Med
             * @description 커브 반영 민평대비 중앙값. 뺄 수 있었던 오퍼가 절반이 안 되면 None
             */
            bpc_med?: number | null;
            /** Ytm Med */
            ytm_med?: number | null;
            /** Ttm Lo */
            ttm_lo?: number | null;
            /** Ttm Hi */
            ttm_hi?: number | null;
        };
        /**
         * CreditQuote
         * @description 크레딧 매도 호가. ★이 시장은 반쪽이다 — 종목을 찍은 레벨 호가의 99.9%가 매도다.
         */
        CreditQuote: {
            /** T */
            t: number;
            /** S */
            s?: ("S" | "B") | null;
            /**
             * N
             * @description 종목/발행체 표시명
             */
            n?: string | null;
            /**
             * Unit
             * @description 문면 표기 단위
             */
            unit?: ("bp" | "원") | null;
            /**
             * Atmp
             * @description 문면에 값이 없어 «민평 그 자리» 로 읽은 오퍼 [OWNER 2026-09-07]
             */
            atmp?: boolean | null;
            /**
             * Bp
             * @description 민평 대비 bp (bp 표기 행)
             */
            bp?: number | null;
            /**
             * Dbp
             * @description 민평 대비 bp (원 표기 행 — 끝전 환산 또는 문면 Δ)
             */
            dbp?: number | null;
            /**
             * Bpe
             * @description 하류가 하나로 쓰는 민평 대비 bp
             */
            bpe?: number | null;
            /**
             * Bpc
             * @description 커브 반영 민평대비 = bpe − 같은 잔존 국고 커브의 오늘 이동. 닻이 둘 미만이면 None 이다(0 이 아니다)
             */
            bpc?: number | null;
            /**
             * Cmv
             * @description 그 잔존에서 «뺀 양»(bp) — 화면이 되짚게 한다
             */
            cmv?: number | null;
            /**
             * Pr
             * @description 같은 무리 안 순위. 1 = 가장 싸다(금리가 가장 높다)
             */
            pr?: number | null;
            /**
             * Pn
             * @description 그 무리에서 값을 부른 오퍼 수. 넷 미만이면 순위를 안 낸다
             */
            pn?: number | null;
            /**
             * Pk
             * @description 무리 이름 — «계열 등급 잔존칸», 넷이 안 되면 등급을 품어 «계열 잔존칸»
             */
            pk?: string | null;
            /**
             * Padj
             * @description 그 무리를 커브 반영값으로 줄 세웠나(전원이 가졌을 때만)
             */
            padj?: boolean | null;
            /**
             * Pmed
             * @description 그 무리의 중앙값 — `padj` 가 참이면 커브반영값의, 아니면 민평대비의. 알람(`alarm_hits`)과 교정기(`alarm_sizing`)가 **이 값 하나**를 쓴다. 무리를 두 곳이 만들면 한쪽만 고치게 되므로 여기 싣는다 [2026-10-01]
             */
            pmed?: number | null;
            /**
             * Won
             * @description 문면 원 스프레드
             */
            won?: number | null;
            /** Ytm */
            ytm?: number | null;
            /**
             * Y
             * @description ytm 과 같다(피드 호환)
             */
            y?: number | null;
            /**
             * Mp
             * @description 문면에 적힌 전일 민평
             */
            mp?: number | null;
            /**
             * Ttm
             * @description 잔존(년)
             */
            ttm?: number | null;
            /** Matd */
            matd?: string | null;
            /**
             * Cls
             * @description 종별 — 위험순(무위험·특은채·은행채·카드채·캐피탈·회사채·유동화·MBS)
             */
            cls?: string | null;
            /**
             * Cls2
             * @description cls 와 같다 — 위험순 계열이 이미 카드·캐피탈을 가른다(2026-09-10)
             */
            cls2?: string | null;
            /**
             * Rt
             * @description 신용등급
             */
            rt?: string | null;
            /** Rt Src */
            rt_src?: ("문면" | "집계") | null;
            /**
             * Cats
             * @description 범주 콜 매칭용 섹터
             */
            cats?: string[] | null;
            /**
             * Mb
             * @description 이 오퍼에 맞는 매수 니즈 수
             */
            mb?: number | null;
            /**
             * Frac
             * @description 끝전 — 전일 민평 단가의 소수부
             */
            frac?: number | null;
            /** Fsrc */
            fsrc?: ("stated" | "list" | "assumed") | null;
            /**
             * Lvl
             * @description quoted=문면 금리 · conv=끝전 환산 · est=0.5 가정
             */
            lvl?: ("quoted" | "conv" | "est") | null;
            /**
             * Chk
             * @description Q 행의 대사값(우리 환산 − 문면 금리, bp)
             */
            chk?: number | null;
            /** A */
            a?: number | null;
            /** Asrc */
            asrc?: ("stated" | "implied" | "bare" | "default" | "oddlot" | "inherit") | null;
            /** D */
            d?: string | null;
            /** K */
            k?: string | null;
        };
        /** Curve */
        Curve: {
            /** Offers */
            offers: components["schemas"]["CurveOffer"][];
            /**
             * Mp Line
             * @description [[잔존, 민평 중앙값, 표본수], …]
             */
            mp_line: unknown[][];
            /**
             * Mp N
             * @default 0
             */
            mp_n: number;
        };
        /**
         * CurveAnchor
         * @description 커브 이동의 닻 한 칸 — 그 만기 칸 국고 종목들의 «오늘 mid − 전일 민평» 중앙값.
         *
         *     칸은 민평 기준선과 같다(2년 미만 0.25년 · 그 위 0.5년). 한 칸에 여럿이고 그중
         *     10분 안쪽이 있으면 **그것들만** 쓴다 — 두 시간 묵은 닻이 커브를 붙잡지 않게.
         */
        CurveAnchor: {
            /**
             * Ttm
             * @description 칸 중심(년)
             */
            ttm: number;
            /**
             * Bp
             * @description 그 칸의 이동(bp)
             */
            bp: number;
            /**
             * N
             * @description 이 칸을 세운 종목 수
             */
            n: number;
            /**
             * Age
             * @description 가장 신선한 닻의 나이(초). 0 = 지금 양면이 서 있다
             */
            age?: number | null;
            /**
             * Cs
             * @description 이 칸을 세운 종목(회차) — 손으로 되짚으라고 싣는다
             */
            cs: string[];
        };
        /**
         * CurveMove
         * @description 오늘 국고 커브가 잔존별로 얼마나 움직였나 [OWNER 2026-09-28].
         *
         *     크레딧의 «민평대비» 에서 이것을 빼면 «시장이 움직인 만큼» 이 아니라
         *     «이 종목이 싸졌다» 만 남는다. 통과 계수 β 0.823 · R² 0.643(원장 138,032 종목일).
         *     β 를 곱하지 않고 통째로 뺀다 — 남는 오차가 0.57 대 0.55bp 로 사실상 같고,
         *     통째로 뺀 값은 오너가 닻을 보고 손으로 되짚을 수 있다.
         */
        CurveMove: {
            /** Pts */
            pts: components["schemas"]["CurveAnchor"][];
            /** N */
            n: number;
            /**
             * Ok
             * @description 닻이 둘 이상인가. False 면 화면은 이 칸을 비운다
             */
            ok: boolean;
            /** Lo */
            lo?: number | null;
            /** Hi */
            hi?: number | null;
            /**
             * Med
             * @description 닻 칸들의 중앙 이동(bp) — 머리줄에 적는 수
             */
            med?: number | null;
            /**
             * Age Max
             * @description 가장 낡은 닻의 나이(초)
             */
            age_max?: number | null;
        };
        /** CurveOffer */
        CurveOffer: {
            /** N */
            n?: string | null;
            /** Ttm */
            ttm?: number | null;
            /** Ytm */
            ytm?: number | null;
            /** Bpe */
            bpe?: number | null;
            /**
             * Bpc
             * @description 커브 반영 민평대비
             */
            bpc?: number | null;
            /** A */
            a?: number | null;
            /**
             * Mb
             * @default 0
             */
            mb: number;
            /** Lvl */
            lvl?: ("quoted" | "conv" | "est") | null;
        };
        /**
         * CurveTodayRow
         * @description 커브 오늘의 한 줄 — 종목 행에 «전일민평 대비» 와 «딜러 수» 를 얹은 것.
         */
        CurveTodayRow: {
            /** C */
            c: string;
            /** Nm */
            nm?: string | null;
            /** Full */
            full?: string | null;
            /** Alias */
            alias?: string | null;
            /** Ten */
            ten?: string | null;
            /** Mat */
            mat?: string | null;
            /** Mp */
            mp?: number | null;
            /** Mpd */
            mpd?: string | null;
            /** @description 최우선 오퍼 */
            fa?: components["schemas"]["Quote"] | null;
            /** @description 최우선 비드 */
            fb?: components["schemas"]["Quote"] | null;
            /** Mid */
            mid?: number | null;
            /**
             * Fill
             * @description 당일 마지막 체결 {t, y}
             */
            fill?: {
                [key: string]: unknown;
            } | null;
            /**
             * Bench
             * @default false
             */
            bench: boolean;
            /**
             * Next
             * @default false
             */
            next: boolean;
            /**
             * Today
             * @default false
             */
            today: boolean;
            /**
             * N
             * @default 0
             */
            n: number;
            /**
             * Nq
             * @default 0
             */
            nq: number;
            /**
             * Npx
             * @default 0
             */
            npx: number;
            /**
             * Hn
             * @default 0
             */
            hn: number;
            /**
             * Pv
             * @description 어제 책의 그 종목
             */
            pv?: {
                [key: string]: unknown;
            } | null;
            /**
             * Dbp
             * @description mid − 전일민평, bp
             */
            dbp?: number | null;
            /**
             * Nd
             * @description 오늘 오퍼 딜러 · 비드 딜러 수
             * @default
             */
            nd: string;
            /**
             * Imb
             * @description 지금 불균형 (비드 딜러 − 오퍼 딜러)/합. 양면일 때만(+++)
             */
            imb?: number | null;
        };
        /**
         * DealerCard
         * @description 이 종목에 선 딜러 하나 — 가장 최근 오퍼/비드 한 건씩.
         */
        DealerCard: {
            /** K */
            k?: string | null;
            /** D */
            d?: string | null;
            S?: components["schemas"]["Quote"] | null;
            B?: components["schemas"]["Quote"] | null;
            /**
             * N
             * @description 오늘 이 종목에 낸 호가 건수
             * @default 0
             */
            n: number;
            /**
             * Ab S
             * @description 오늘 최우선 오퍼에 서 있던 시간(초)
             * @default 0
             */
            ab_s: number;
            /**
             * Ab B
             * @description 오늘 최우선 비드에 서 있던 시간(초)
             * @default 0
             */
            ab_b: number;
            /**
             * Fresh
             * @default 0
             */
            fresh: number;
            /**
             * Both
             * @default false
             */
            both: boolean;
        };
        /** DealerCards */
        DealerCards: {
            /**
             * Rows
             * @default []
             */
            rows: components["schemas"]["DealerCard"][];
            /**
             * N
             * @default 0
             */
            n: number;
            /**
             * N Both
             * @default 0
             */
            n_both: number;
            /** Fa Y */
            fa_y?: number | null;
            /** Fb Y */
            fb_y?: number | null;
        };
        /**
         * Event
         * @description 책의 «움직임». first=오늘 첫 호가 · best=최우선 갱신 · cross=남의 반대편을 뚫음
         *     · size=대량 · fill=체결. ★같은 레벨에서 만나는 «락» 은 이벤트가 아니다(하루 907건).
         */
        Event: {
            /** T */
            t: number;
            /**
             * K
             * @enum {string}
             */
            k: "first" | "best" | "cross" | "size" | "fill";
            /** Lane */
            lane?: ("ktb" | "msb" | "nhb" | "cr" | "muni") | null;
            /** Code */
            code?: string | null;
            /** N */
            n?: string | null;
            /** S */
            s?: ("S" | "B") | null;
            /** Y */
            y?: number | null;
            /** A */
            a?: number | null;
            /** D */
            d?: string | null;
            /**
             * X
             * @description 종류별 곁가지(이전 최우선·뚫은 상대·귀속 등급)
             */
            x?: {
                [key: string]: unknown;
            } | null;
        };
        /** FeedPage */
        FeedPage: {
            /** Feed */
            feed: components["schemas"]["FeedRow"][];
            /** N Seq */
            n_seq: number;
        };
        /**
         * FeedRow
         * @description 메시지 한 줄. 파싱 결과를 원문과 나란히 흘린다.
         */
        FeedRow: {
            /**
             * I
             * @description 적재 일련번호. 화면이 이걸로 이어 붙인다
             */
            i: number;
            /** T */
            t: number;
            /**
             * R
             * @description 방
             */
            r?: string | null;
            /**
             * K
             * @description 종류 QUOTE·AXE·CONFIRM·INQUIRY·THANKS·OTHER
             */
            k?: string | null;
            /** Sec */
            sec?: string | null;
            /** N */
            n?: string | null;
            /** Code */
            code?: string | null;
            /** S */
            s?: ("S" | "B") | null;
            /** Y */
            y?: number | null;
            /** Bp */
            bp?: number | null;
            /**
             * Mp
             * @description 어제자 민평 — 국고·통안은 DB 전일 민평, 크레딧·국주·MBS 는 문면에 적힌 민평
             */
            mp?: number | null;
            /**
             * Px
             * @description 단가 — 액면 10,000원당. 관행적 복할인(국고·외평 06M · 통안 03M)
             */
            px?: number | null;
            /**
             * Pxs
             * @description 단가의 결제일 규약 — 'T'(당일) 또는 'T+1'(익일). 휴일표가 없어 지금은 T
             */
            pxs?: string | null;
            /**
             * Pxb
             * @description 단가의 기준 — 'q'(이 행의 할인조정) 또는 'mp'(값이 없어 전일 민평으로 냄)
             */
            pxb?: string | null;
            /**
             * Mat
             * @description 만기일 YYYY-MM-DD — 종목의 속성이라 값이 없는 행에도 선다
             */
            mat?: string | null;
            /**
             * Ttm
             * @description 잔존 연수 — 결제일 기준
             */
            ttm?: number | null;
            /**
             * Pxa
             * @description 1이면 쿠폰을 «전일 민평과 같다»고 가정해 낸 단가 — 절대 수준은 믿지 말 것(수정가액은 쓸 만하다)
             */
            pxa?: number | null;
            /**
             * Won
             * @description 수정가액 — 전일 민평 대비 «원». +원 = 단가 비쌈 = 금리 낮음
             */
            won?: number | null;
            /**
             * Chk
             * @description 검산 O/X — 이 행의 «단가를 믿어도 되나». 못 재면 비운다
             */
            chk?: string | null;
            /**
             * Chkw
             * @description X 인 이유(만기 임박·민평이 오늘 것이 아님·단가가 상식 밖)
             */
            chkw?: string | null;
            /** A */
            a?: number | null;
            /** Asrc */
            asrc?: ("stated" | "implied" | "bare" | "default" | "oddlot" | "inherit") | null;
            /** Atmp */
            atmp?: boolean | null;
            /** Csrc */
            csrc?: ("stated" | "level" | "prev") | null;
            /** Lvl */
            lvl?: ("quoted" | "conv" | "est") | null;
            /**
             * P
             * @description 브로커 이름 — 메신저 대화명(이름 가림이 켜져 있으면 P### 라벨)
             */
            p?: string | null;
            /**
             * D
             * @description 데스크 표시명 «유진증권 CM팀» (가림이면 H##-#)
             */
            d?: string | null;
            /**
             * Bk
             * @description 딜러 키 — 전화 정규화 값이라 전화 가림에 묶인다(K###)
             */
            bk?: string | null;
            /**
             * H
             * @description 하우스 «유진» (가림이면 H##)
             */
            h?: string | null;
            /** Raw */
            raw?: string | null;
        };
        /**
         * GradeCurve
         * @description 등급별 민평 커브 한 벌(`sim_portfolio.credit_matrix` 최신 행).
         */
        GradeCurve: {
            /** Group */
            group?: string | null;
            /** Date */
            date?: string | null;
            /** Label */
            label?: string | null;
            /**
             * Pts
             * @default []
             */
            pts: components["schemas"]["GradePoint"][];
        };
        /** GradePoint */
        GradePoint: {
            /** Ttm */
            ttm: number;
            /** Y */
            y: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Heat
         * @description 칸 열쇠는 «종별|등급|버킷». 등급 자리가 `*` 인 칸은 등급을 무시하고 합친 것이다
         *     (화면의 «등급 무시» 토글이 쓴다). 국고·통안 행은 등급이 없어 `미상` 으로 온다.
         */
        Heat: {
            /** Cells */
            cells: {
                [key: string]: components["schemas"]["HeatCell"];
            };
            /**
             * Stale
             * @description 통안 민평이 그날 것이 아니다
             * @default false
             */
            stale: boolean;
            /** Rows */
            rows: unknown[][];
            /** Buckets */
            buckets: string[];
        };
        /** HeatCell */
        HeatCell: {
            /** Med */
            med?: number | null;
            /**
             * N
             * @default 0
             */
            n: number;
            /** Lo */
            lo?: number | null;
            /** Hi */
            hi?: number | null;
            /**
             * Est
             * @description 그 칸에 든 «추정»(끝전 0.5 가정) 건수
             * @default 0
             */
            est: number;
        };
        /** ImbCell */
        ImbCell: {
            /**
             * N
             * @default 0
             */
            n: number;
            /**
             * Pb
             * @description 그 구간에서 «사 감»(오퍼가 맞음) 비율 %
             */
            pB?: number | null;
        };
        /** LeaderRow */
        LeaderRow: {
            /** K */
            k?: string | null;
            /** D */
            d?: string | null;
            /**
             * N
             * @default 0
             */
            n: number;
            /**
             * Ln
             * @description 고른 레인에서의 건수
             * @default 0
             */
            ln: number;
            /**
             * S
             * @default 0
             */
            s: number;
            /**
             * B
             * @default 0
             */
            b: number;
            /**
             * C
             * @default 0
             */
            c: number;
            /**
             * Ab
             * @description 오늘 최우선에 서 있던 시간 합(초)
             * @default 0
             */
            ab: number;
            /**
             * F
             * @description 오늘 귀속된 체결 — 맞은 호가의 주인으로 센다(+++)
             * @default 0
             */
            f: number;
            /** First */
            first?: number | null;
            /** Last */
            last?: number | null;
            /**
             * Lane
             * @default {}
             */
            lane: {
                [key: string]: number;
            };
            /**
             * Codes
             * @default []
             */
            codes: unknown[][];
        };
        /** Leaderboard */
        Leaderboard: {
            /**
             * Rows
             * @default []
             */
            rows: components["schemas"]["LeaderRow"][];
            /**
             * N
             * @default 0
             */
            n: number;
            /**
             * Shown
             * @default 0
             */
            shown: number;
        };
        /** ObBest */
        ObBest: {
            fa?: components["schemas"]["Quote"] | null;
            fb?: components["schemas"]["Quote"] | null;
            /** Spread Bp */
            spread_bp?: number | null;
            /** Mid */
            mid?: number | null;
            /**
             * Lock
             * @description 락 — 같은 레벨에 오퍼와 비드가 함께 서 있다(스프레드 0). 걷지 않고 양면을 세운다 [OWNER 2026-09-15]. 체결의 23.5%가 이 자리에서 난다
             * @default false
             */
            lock: boolean;
        };
        /**
         * ObLadder
         * @description 종목 하나의 호가 사다리. 막대 폭·나이 칩은 값이 아니라 표현이라 여기 없다.
         */
        ObLadder: {
            /** Code */
            code: string;
            /**
             * Agg
             * @default 0
             */
            agg: number;
            /**
             * Levels
             * @default []
             */
            levels: components["schemas"]["ObLevel"][];
            /**
             * Implied
             * @description 교체에서 나온 조건부 호가
             * @default []
             */
            implied: {
                [key: string]: unknown;
            }[];
            /**
             * Basis
             * @default n
             * @enum {string}
             */
            basis: "amt" | "n";
            /**
             * Mx
             * @default 1
             */
            mx: number;
            /**
             * @default {
             *       "a": 0,
             *       "b": 0,
             *       "na": 0,
             *       "nb": 0,
             *       "imp_a": 0,
             *       "imp_b": 0
             *     }
             */
            sum: components["schemas"]["ObSum"];
            /**
             * @default {
             *       "lock": false
             *     }
             */
            best: components["schemas"]["ObBest"];
        };
        /** ObLevel */
        ObLevel: {
            /** Y */
            y: number;
            S?: components["schemas"]["ObSide"] | null;
            B?: components["schemas"]["ObSide"] | null;
            /**
             * Atmp
             * @default false
             */
            atmp: boolean;
            /**
             * Blank
             * @description 집계 격자의 빈 칸
             */
            blank?: ("a" | "b") | null;
        };
        /**
         * ObSide
         * @description 사다리 한 칸의 한 면. 화면은 이걸 막대로 그리기만 한다.
         */
        ObSide: {
            /** N */
            n: number;
            /** Amt */
            amt: number;
            /**
             * Unk
             * @description 수량 표기가 없던 호가 수
             * @default 0
             */
            unk: number;
            /**
             * Dflt
             * @description 표기가 없어 기본단위 100억으로 본 수
             * @default 0
             */
            dflt: number;
            /**
             * Odd
             * @description 자투리
             * @default 0
             */
            odd: number;
            /**
             * Atmp
             * @description «민평에» 라고만 한 호가 수
             * @default 0
             */
            atmp: number;
            /**
             * Fresh
             * @description 그 칸에서 가장 신선한 호가의 장중 초
             * @default 0
             */
            fresh: number;
            /**
             * Hit
             * @description 그 칸에서 «실제로 체결된» 호가 수 (v12 체결 귀속)
             * @default 0
             */
            hit: number;
            /**
             * Fhit
             * @description 그 칸의 마지막 체결 시각(장중 초). 0 이면 없음
             * @default 0
             */
            fhit: number;
            /**
             * Who
             * @default []
             */
            who: (string | null)[];
        };
        /** ObSum */
        ObSum: {
            /**
             * A
             * @default 0
             */
            a: number;
            /**
             * B
             * @default 0
             */
            b: number;
            /**
             * Na
             * @default 0
             */
            na: number;
            /**
             * Nb
             * @default 0
             */
            nb: number;
            /**
             * Imp A
             * @default 0
             */
            imp_a: number;
            /**
             * Imp B
             * @default 0
             */
            imp_b: number;
        };
        /**
         * Pulse
         * @description 시장 맥박. 화면은 칸 값을 막대로 그리기만 한다.
         */
        Pulse: {
            /**
             * Bin
             * @default 600
             */
            bin: number;
            /**
             * Bins
             * @default []
             */
            bins: components["schemas"]["PulseBin"][];
            /**
             * Prev Bins
             * @default []
             */
            prev_bins: components["schemas"]["PulsePrevBin"][];
            /**
             * Nq
             * @default 0
             */
            nq: number;
            /**
             * Na
             * @default 0
             */
            na: number;
            /**
             * Nc
             * @default 0
             */
            nc: number;
            /**
             * Ni
             * @default 0
             */
            ni: number;
            /**
             * Ktb
             * @default 0
             */
            ktb: number;
            /**
             * Cr
             * @default 0
             */
            cr: number;
            /**
             * Msb
             * @default 0
             */
            msb: number;
            /**
             * Vs Prev Pct
             * @description 어제 같은 시각까지 누적 대비 %
             */
            vs_prev_pct?: number | null;
            /**
             * N Dealer
             * @default 0
             */
            n_dealer: number;
            /** Prev N Dealer */
            prev_n_dealer?: number | null;
            /**
             * N Event
             * @default 0
             */
            n_event: number;
            /** T0 */
            t0?: number | null;
            /** T1 */
            t1?: number | null;
        };
        /** PulseBin */
        PulseBin: {
            /**
             * T
             * @description 칸의 시작 장중 초
             */
            t: number;
            /**
             * Q
             * @default 0
             */
            q: number;
            /**
             * A
             * @default 0
             */
            a: number;
            /**
             * C
             * @default 0
             */
            c: number;
            /**
             * I
             * @default 0
             */
            i: number;
            /**
             * O
             * @default 0
             */
            o: number;
        };
        /** PulsePrevBin */
        PulsePrevBin: {
            /** T */
            t: number;
            /**
             * N
             * @default 0
             */
            n: number;
        };
        /**
         * PxFill
         * @description 오늘 이 종목의 체결 하나 — 테이프(`snap.tape`)에서 고른다. 화면은 점으로 찍는다.
         */
        PxFill: {
            /** T */
            t: number;
            /** Y */
            y: number;
            /**
             * A
             * @description 억
             */
            a?: number | null;
            /**
             * D
             * @description 딜러 표시명
             */
            d?: string | null;
        };
        /**
         * PxHist
         * @description `/api/px_hist` 의 응답 — 한 종목의 «어제까지» 분 단위 매도·매수와 그날의 전일 민평.
         *
         *     [OWNER 2026-10-01] 「어제자랑 연결해서 최대 1년까지」. 오늘은 `/api/view` 의 `px` 가
         *     (10초 표본) 내고, 화면이 둘을 한 줄로 잇는다. 국고만 이력이 있다(`kbond_px_hist` 머리말).
         */
        PxHist: {
            /** Code */
            code: string;
            /**
             * Days
             * @description 호가가 있던 영업일, 오름차순 'YYYY-MM-DD'. `q` 의 첫 칸이 이 순번이다
             * @default []
             */
            days: string[];
            /**
             * Q
             * @description [날 순번, 장중 분, 매수, 매도] — 그 분의 마지막 호가. 없는 쪽은 null
             * @default []
             */
            q: (number | null)[][];
            /**
             * Mp
             * @description `days` 와 같은 길이 — 그날의 전일 민평
             * @default []
             */
            mp: (number | null)[];
            /**
             * Asof
             * @description 마지막 날
             */
            asof?: string | null;
            /** Note */
            note?: string | null;
        };
        /** PxPoint */
        PxPoint: {
            /** T */
            t: number;
            /** Mid */
            mid?: number | null;
            /**
             * A
             * @description 그 시각의 최우선 오퍼
             */
            a?: number | null;
            /**
             * B
             * @description 그 시각의 최우선 비드
             */
            b?: number | null;
        };
        /**
         * PxSeries
         * @description 시세 이력. 세로 범위는 규칙이라 서버가 낸다(민평 대칭).
         */
        PxSeries: {
            /** Code */
            code: string;
            /** Mp */
            mp?: number | null;
            /** Lo */
            lo?: number | null;
            /** Hi */
            hi?: number | null;
            /** T0 */
            t0?: number | null;
            /** T1 */
            t1?: number | null;
            /**
             * Bin
             * @default 600
             */
            bin: number;
            /**
             * Pts
             * @default []
             */
            pts: components["schemas"]["PxPoint"][];
            /**
             * Act
             * @default []
             */
            act: components["schemas"]["ActBin"][];
            /**
             * Fills
             * @description 오늘 체결 전부(시간순) — 화면이 점으로 찍는다 [OWNER 2026-10-01]
             * @default []
             */
            fills: components["schemas"]["PxFill"][];
            /**
             * Note
             * @description 표본이 모자라면 그 이유
             */
            note?: string | null;
        };
        /**
         * Quote
         * @description 국고·통안·국민주택의 한 호가. (딜러, 방향, 종목) 하나에 하나뿐이다 — 절대값 교체.
         */
        Quote: {
            /**
             * T
             * @description 장중 초(00:00:00 부터)
             */
            t: number;
            /**
             * S
             * @description S=매도(오퍼) · B=매수(비드)
             */
            s?: ("S" | "B") | null;
            /**
             * Y
             * @description 수익률(%). 없으면 레벨 미상이다
             */
            y?: number | null;
            /**
             * Code
             * @description 국고 '25-10' · 통안 만기일 · 국주 사다리 칸
             */
            code?: string | null;
            /**
             * A
             * @description 수량(억). 표기가 없으면 기본단위 100
             */
            a?: number | null;
            /** Asrc */
            asrc?: ("stated" | "implied" | "bare" | "default" | "oddlot" | "inherit") | null;
            /**
             * D
             * @description 딜러 표시명. 가림이 켜져 있으면 'H01-2'
             */
            d?: string | null;
            /**
             * K
             * @description 딜러 키. 가림이 켜져 있으면 'K001'
             */
            k?: string | null;
            /**
             * Atmp
             * @description 레벨 없이 «민평에» 한다는 뜻의 호가
             */
            atmp?: boolean | null;
            /**
             * Mp
             * @description 그 종목의 전일 민평(통안·국주만 싣는다)
             */
            mp?: number | null;
            /**
             * Mpd
             * @description 그 민평의 일자. 오늘이 아니면 «전일 대비»가 아니다
             */
            mpd?: string | null;
            /**
             * Qr
             * @description 축약호가 원문(국주)
             */
            qr?: number | null;
        };
        /** SwapBook */
        SwapBook: {
            /**
             * N
             * @default 0
             */
            n: number;
            /**
             * Pairs
             * @default []
             */
            pairs: components["schemas"]["SwapPair"][];
        };
        /** SwapPair */
        SwapPair: {
            /** Pair */
            pair?: string | null;
            /**
             * Asks
             * @default []
             */
            asks: {
                [key: string]: unknown;
            }[];
            /**
             * Bids
             * @default []
             */
            bids: {
                [key: string]: unknown;
            }[];
            /**
             * Spread Bp
             * @description 신형−구형 bp. ×100 하지 않는다
             */
            spread_bp?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * View
         * @description `/api/view` 의 응답. 화면은 이걸 그대로 그린다.
         */
        View: {
            /** Now */
            now?: string | null;
            /** T */
            T: number;
            /**
             * Ttl Mode
             * @default def
             * @enum {string}
             */
            ttl_mode: "def" | "half" | "inf";
            /**
             * Age Steps
             * @description 바램 문턱(초) [신선, 익음]. 화면은 이 값을 쓰고 스스로 정하지 않는다. 근거 = 최우선 나이별 «그 레벨에서 체결» 비율 ~1분 90.6% · 1~5분 61.2% · 5~15분 29.6%
             * @default [
             *       60,
             *       300
             *     ]
             */
            age_steps: number[];
            /** Ver */
            ver?: number | null;
            /** Counts */
            counts: {
                [key: string]: number;
            };
            heat: components["schemas"]["Heat"];
            /**
             * Rows
             * @description lane 이 ktb·msb·nhb 일 때
             */
            rows?: components["schemas"]["BondRow"][] | null;
            /**
             * Axes
             * @description 레벨 없는 «관심» — 책이 아니다
             */
            axes?: components["schemas"]["Axis"][] | null;
            /**
             * Classes
             * @description lane 이 cr 일 때 분류 줄의 구성 — 국고·통안·위험순 계열 여덟
             */
            classes?: components["schemas"]["ClsPill"][] | null;
            /**
             * Buckets
             * @description lane 이 cr 일 때. 국고·통안을 고르면 만기 버킷으로 접힌다
             */
            buckets?: components["schemas"]["CreditBucket"][] | null;
            curve?: components["schemas"]["Curve"] | null;
            /** @description lane 이 cr 이고 국고·통안이 아닐 때. 국고 화면에는 없다 — 닻이 자기 자신이라 순환이다 */
            curve_move?: components["schemas"]["CurveMove"] | null;
            /**
             * Mtx Group
             * @description credit_matrix 의 bond_type(등급 커브)
             */
            mtx_group?: string | null;
            /** @description 고른 종목의 호가 사다리 */
            ob?: components["schemas"]["ObLadder"] | null;
            /** @description 누가 어디 서 있나 */
            dealers?: components["schemas"]["DealerCards"] | null;
            /** @description 교체 책(국고만) */
            swap?: components["schemas"]["SwapBook"] | null;
            /** @description 고른 종목의 시세 이력 */
            px?: components["schemas"]["PxSeries"] | null;
            /**
             * Offers
             * @description lane 이 cr 일 때 고른 버킷의 오퍼
             */
            offers?: components["schemas"]["CreditQuote"][] | null;
            /**
             * Needs
             * @description lane 이 cr 일 때 매수 니즈
             */
            needs?: components["schemas"]["Basket"][] | null;
            /** @description 고른 종별·등급의 민평 커브 */
            grade_curve?: components["schemas"]["GradeCurve"] | null;
            pulse?: components["schemas"]["Pulse"] | null;
            /** Events */
            events?: components["schemas"]["Event"][] | null;
            /** Event Counts */
            event_counts?: {
                [key: string]: number;
            } | null;
            /** Curve Today */
            curve_today?: {
                [key: string]: components["schemas"]["CurveTodayRow"][];
            } | null;
            leaderboard?: components["schemas"]["Leaderboard"] | null;
            /**
             * Alarms
             * @description lane 이 cr 일 때. 창(60초) 안에 온 «무리 중앙보다 문턱만큼 싼» 오퍼. 대부분의 순간에 빈 목록이다 — 없는 것과 «아직 안 옴» 은 같은 뜻이다
             */
            alarms?: components["schemas"]["AlarmHit"][] | null;
            /**
             * Alarm N Bp
             * @description lane 이 cr 일 때. 지금 걸린 문턱(bp). 화면은 이 값을 적고 스스로 정하지 않는다
             */
            alarm_n_bp?: number | null;
            /**
             * Aggr
             * @description 당일 공격 방향 집계 {B: 사 간 체결, S: 판 체결}
             */
            aggr?: {
                [key: string]: number;
            } | null;
            /** @description lane 이 dyn 일 때. 책이 말하는 것(+++) */
            book_info?: components["schemas"]["BookInfo"] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: {
                t?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    book_json_book_json_get: {
        parameters: {
            query?: {
                t?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    feed_json_feed_json_get: {
        parameters: {
            query?: {
                t?: string | null;
                since?: number;
                limit?: number;
                h?: string | null;
                d?: string | null;
                k?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_view_api_view_get: {
        parameters: {
            query?: {
                t?: string | null;
                lane?: string;
                ttl?: string;
                cls?: string | null;
                rt?: string | null;
                code?: string | null;
                agg?: number;
                T?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["View"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_alarms_api_alarms_get: {
        parameters: {
            query?: {
                t?: string | null;
                ttl?: string;
                T?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alarms"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_px_hist_api_px_hist_get: {
        parameters: {
            query: {
                code: string;
                days?: number;
                before?: string | null;
                t?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PxHist"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_events_get: {
        parameters: {
            query?: {
                t?: string | null;
                lite?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    index__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
}
